### PR TITLE
implement tradingview library in nuxtjs

### PR DESCRIPTION
**Pull request by trungnqpro**
#### Add example checklist

- [x] **Any** commit does not contain the charting library's code
- [x] Addresses an existing issue: #30
- [ ] The example is added to README.md
- [ ] The example is self-sufficient and contains only necessary files/changes

### CODE REVIEW

**Comment by timocov** [comment]
Hey @trungnqpro,

I'm sorry for such late reply.

I just noticed that there is also integration with https://www.bcnex.net, am I correct?

**Comment by trungnqpro** [comment]
Dear Sir,
Yes, exactly what I did, I’m frontend leader at Bcnex dev team, 
Thanks,

**Comment by timocov** [comment]
@trungnqpro I'm sorry for the delay. Is it possible to make this sample without additional datafeed, so users don't think that it's "part of example and required to impl"? I think we can create another repo with this custom datafeed and put a link to it in https://github.com/tradingview/awesome-tradingview repo.

**Comment by timocov** [comment]
Fixed in #214

**Pull request closed without merging**
